version: '3.8'

services:
  toktorov_link_client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toktorov_link_client
    networks:
      - toktorov_link_client_network
    ports:
      - "5021:3000"
    restart: always

networks:
  toktorov_link_client_network:
    driver: bridge